---
language: ruby
rvm: 2.0.0
env:
  global:
    - secure: "Bx5jzULI3Ul7q43ck2tQwmG4ioasxr9M9EruNLkHJLvqq/rcBZ0nPmC5Zo6jwS50g28ApLQfUniZDvDVDqOX0+UHFsKBoZZj0CQxRQpWlC+4LsnFj6m64b0H0fgbY5KCT9hpiInTbrmHKNbFo/df/xKYNpvU8/opkhA+PLCc46I="
before_script:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake setup > /dev/null'
script: rake build
after_success:
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ "$GH_TOKEN" ] && rake publish > /dev/null'
